import json

def to_ptr(name):
    return "PFN" + name.upper() + "PROC"

header = """// AUTO GENERATED BY ../gl_gen_scripts.py

#ifndef __AUTOGEN_GL_FUNCS_H
#define __AUTOGEN_GL_FUNCS_H

#include "../../external/glcorearb.h"
#include "../gl_load.h"

#include <gl/GL.h>

namespace vapour { 
namespace render { 
namespace gl {

"""

footer = """

\tvoid __autogen_load_all();
}
}
}

#endif"""

funcs = json.load(open("generated/function_names.json"))

h = open("generated/gl_funcs.h", 'w')
h.close()

h = open("generated/gl_funcs.h", 'a')

h.write(header)

for i in funcs:
    ptr = to_ptr(i)
    h.write("\tstatic " + ptr + (" " * (60 - len(ptr))) + funcs[i] + ";\n")

h.write(footer)
h.close()

c = open("generated/gl_funcs.cpp", 'w')
c.close()

c = open("generated/gl_funcs.cpp", 'a')

c.write("""#include "gl_funcs.h"
        
void vapour::render::gl::__autogen_load_all() {
""")

for i in funcs:
    ptr = to_ptr(i)
    c.write("\tvapour::render::gl::" + funcs[i] + (" " * (50 - len(funcs[i]))) + "= (" + ptr + ")"+ (" " * (60 - len(ptr))) +"vapour::render::gl::load_func( \"" + i + "\" );\n")

c.write("}")

c.close()